-- AlterTable
ALTER TABLE "content_list" ALTER COLUMN "h_ct" SET DATA TYPE VARCHAR(80),
ALTER COLUMN "h_data" SET DATA TYPE VARCHAR(80),
ALTER COLUMN "h_k" SET DATA TYPE VARCHAR(80),
ALTER COLUMN "ct_r" SET DATA TYPE VARCHAR(80);
